spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
app:
  jwt:
    secret: ${JWT_SECRET:25a350c66afc84e2880f5dbcb3671bd0fd27722e7331e6f1420e311e11665edc}
    expiration: 86400000
    header: Authorization
    prefix: "Bearer "
logging:
  level:
    org.springframework.security: DEBUG